language: node_js
sudo: false
node_js:
  - "5.1.0"

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules
    - bower_components

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install
  - bower install
script: gulp
